# This is workflow name
name: hello

# runs on trigger
on:   
  push:
    branches: [main]
    
# these are jobs inside the workflow
jobs:

# This is the name of jobs
  greet:
   # this is github runner
    runs-on: ubuntu-latest
    steps:
     - name: say hello to users
       run: echo "Hello Dosto"

     - name: say hello to username
       run: echo "Hello $USER"
      
